---
title: "Journal"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

### 2026 | 10 | 09

Doing some debug works.

(13:51) Testing.

這星期已經是第三個人問我網站怎麽製作了。純粹用html, javascript和css看著有點費勁，尤其是html文件一堆tag.用Rmarkdown和github製作網站就非常舒服。但我發現有些地方不得不使用html. I need to learn more.

(16:12) Bowen ratio的計算真是方便啊，但方便是方便，它對測量的準確度要求太高了，僅改變2%的濕度與0.5的氣溫便造成29%的誤差。這導致我使用Bowen ratio算出來的東西都是垃圾，以至於離譜到日閒的蒸發量變成了負數。我檢查了幾次，我輸入的公式在數學上是沒有錯誤的。還是要乖乖去用residual energy balance吧。

### 2026 | 10 | 07

昨天和導師開會主要在討論scientific writing和AI在寫作中的運用。

Scientific writing是在學術訓練中很重要的一部分，而我寫的東西都是狗屎。總的introduction和每一個章節的introduction都要大改，導師說我paragraph有很大的問題，sentence是disconnected.然後發了我一些寫作的資料。

關於如何恰儅地在學術寫作中使用AI，我終於問到了一個明確的答案。導師表示你可以把你的初稿喂給AI，讓AI修改文法潤色，再把修改後的稿發她——這樣看起來也順暢點，不會全篇文法錯誤影響閲讀，同時也是own ideas.

向導師吹牛逼在下周二前完成proposal的修改。

今日目標：(1) 看完Thinking about your writing, introduction slides, paragraph slides. (2) 修改RQ1.

(16:43 update) 看完Thinking about your writing, introduction slides, paragraph slides.

### 2026 | 10 | 06

今日與WAARC的人meeting,她問了我的background,并表示香港真的有農業嗎，怎麽我會去讀agrivoltaic phd?

我表示我是GIS出生的，在讀碩士期間幫一個農業咨詢公司分析地理數據。隨後我發現農民需要那些數據，而地理數據分析又恰好是我擅長的。所以做碩士論文的時候我的相關題目是分析西澳某農場的碳與水動態。在碩士畢業后我問了碩導有沒有博士名額，碩導說有，所以我就讀博了。我坦白我不瞭解農業，我只是喜歡科研，做數據分析，并從數據中發現故事。

WAARC的人隨後表示，現代農業確實需要跨行業的人。

Agrivoltaic這個項目，我一不懂農業，二不懂工程。比起本碩博一路相關領域上來的人，也有在業界積纍沉澱了很多年的人，我需要投入更多的努力，填補我的知識空白。

這就是科學之美。學科不是獨立的，它們是緊密相連的。

### 2026 | 10 | 05

立flag, 今日一定要改完introduction.

改完之後再係尼度update.

(9:56) 在office工作經常被打斷。Office有11個人，進進出出，與別人説話，跟我説話，借東西。我要想一個功能，隱藏部分日記内容。今日先把introduction搞定。

(16:01) 點解成日有人同我講野？我好難focus吖。

(23:59) 新的comments來了，我又回到被introduction支配的恐懼了。

### 2026 | 10 | 03 

某次一哥們問我：你能感受到科學之美嗎？我回答：這就是我讀博的理由。

這番話把我拉回本科階段。Prof Zhu是我本科導師，我當時的畢業論文是使用光學遙感做野火分析。在讀博開始前一周我回PolyU看望Prof Zhu, 教授順便把我拉去了他的組會，這麽介紹我：最早的學生之一，被我忽悠著去做科研的。

那麽多年過去，我終於走上了科研的路。只是有點遺憾，我大概無緣光學遙感了。

### 2026 | 10 | 02 

**講講這個repo的本意**

我的本意是創建一個網站來記錄PhD學習的過程。初步構想是使用Rmarkdown及一個開源github page搭建一個網站。但是對兩者都知之甚少。基於此，我便先記錄在Rmarkdown上面，等後續有時間再慢慢補全。

日記部分主要會以中文形式呈現，學習筆記以英文爲主，中文為輔。

**再講講AI在科研中的運用**

這段時間我在修改PhD開題報告。遇到的一個很大的問題是導師寫了很多so what類的評論。我試著把我寫的狗屎原文投喂給3個AI，分別是Claude, Chatgpt與Gemini.

Claude (free) 給我的感覺是一個非常嚴厲的導師，話不多而句句切中痛點。Chatgpt (free) 大概被我用壞了，回復很長，囉囉嗦嗦講了上千字，有點點在奉承。Gemini (plus) 只改了幾個語法錯誤，更適合來讀文獻。

（16：59 update）我今日白天在學校無心科研，時間都用來研究怎麽用Rmarkdown創建agrivoltaic學習網站了，一日下來還弄得有模有樣。但是我在修改proposal上卡了太久了，連自己都不想打開文件看一個月前的狗屎，這種情況下除了科研，幹啥都有趣。

以上。